name: Build and Push Add-on

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ADDON_NAME: zerotier-gateway
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build ${{ matrix.arch }} image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch:
          - aarch64
          - amd64
          - armhf
          - armv7
          - i386
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get addon version
        id: version
        run: |
          VERSION=$(grep -E "^version:" "${{ env.ADDON_NAME }}/config.yaml" | sed 's/version: //g' | tr -d '"')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Set build args
        id: build_args
        run: |
          case "${{ matrix.arch }}" in
            "aarch64") BUILD_FROM="ghcr.io/home-assistant/aarch64-base:3.19" ;;
            "amd64") BUILD_FROM="ghcr.io/home-assistant/amd64-base:3.19" ;;
            "armhf") BUILD_FROM="ghcr.io/home-assistant/armhf-base:3.19" ;;
            "armv7") BUILD_FROM="ghcr.io/home-assistant/armv7-base:3.19" ;;
            "i386") BUILD_FROM="ghcr.io/home-assistant/i386-base:3.19" ;;
          esac
          echo "build_from=$BUILD_FROM" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.ADDON_NAME }}
          file: ./${{ env.ADDON_NAME }}/Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.ADDON_NAME }}-${{ matrix.arch }}:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.ADDON_NAME }}-${{ matrix.arch }}:${{ steps.version.outputs.version }}
          build-args: |
            BUILD_FROM=${{ steps.build_args.outputs.build_from }}
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_VERSION=${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max